config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'pages/about'
  get 'orders/user_orders'

  devise_for :users

  resources :posts do
    resources :comments, only:  [:create, :destroy]
  end

  resources :pets

  get '/show_pet', to: 'pets#show_pet'
  get '/hide_pet', to: 'pets#hide_pet'

  resources :services do
    collection do
      get :all_services
    end
  end

  resources :orders
  resources :profiles
  resources :likes, only: [:create, :destroy]

  resources :home do
    get :post, on: :collection
  end

  resources :types

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :post
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, foreign_key: :parent_id
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: [:likeable_id, :likeable_type] }
  belongs_to :user
  belongs_to :user, optional: true
  belongs_to :post , optional: true
  belongs_to :likeable, polymorphic: true
end

app/models/order.rb
class Order < ApplicationRecord


  belongs_to :service
  belongs_to :user

  validates :title, presence: true
  validates :price, presence: true
  validates :service_id, presence: true

end

app/models/page.rb
class Page < ApplicationRecord

end

app/models/pet.rb
class Pet < ApplicationRecord

  belongs_to :user
  has_many :posts, dependent: :destroy
  belongs_to :type

  validates :name, presence: true
  validates :breed, presence: true
  validates :age, presence: true
  validates :gender, presence: true

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  belongs_to :pet
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many_attached :pictures, dependent: :destroy

end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user
  has_one_attached :picture, dependent: :destroy

end

app/models/service.rb
class Service < ApplicationRecord

  belongs_to :user
  has_many :orders, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

end

app/models/type.rb
class Type < ApplicationRecord

  belongs_to :user
  has_many :pets, dependent:  :destroy

end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :services, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :pets, dependent: :destroy
  has_many :types, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [ :show, :edit, :update, :destroy ]
  def index
    @pet = Pet.new
    @pets = current_user.pets
    @types = current_user.types
    @pets = current_user.types.map { |item| item.pets }
  end

  def all_pets
    @pets = current_user.pets(created_at:'desc')
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def edit
    @types =  current_user.types
  end

  def show_pet
    @pet = Pet.find_by(id: params[:id])
    @pet.update!(:status => true)
    redirect_to pets_path
  end

  def hide_pet
    @pet = Pet.find_by(id: params[:id])
    @pet.update!(:status => false)
    redirect_to pets_path
  end


  def create
    @pet = current_user.pets.new(pet_params)

      if @pet.save
        redirect_to pet_path(@pet), notice: "Pet was successfully created."
      else
        render 'new'
      end
    end

  def update
    if @pet.update(pet_params)
        redirect_to pet_path(@pet), notice: "Pet was successfully updated."
      else
        render 'edit'
      end
  end


  def destroy
    @pet.destroy

    redirect_to pets_path, notice: "Pet was successfully destroyed."
  end

  private

    def set_pet
      @pet = current_user.pets.find(params[:id])
    end

    def pet_params
      params.require(:pet).permit(:name, :breed, :gender, :age, :description, :type_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [ :show, :edit, :update, :destroy ]
  def index
    @post = current_user.posts
  end

  def show
    @service = current_user.services
  end

  def new
    @profile = Profile.new
  end

  def edit

  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
      if @profile.save
        redirect_to profile_path(@profile), notice: "Profile was successfully created."
      else
        render 'new'
      end
  end

  def update
      if @profile.update(profile_params)
        redirect_to profile_path(@profile), notice: "Profile was successfully updated."
      else
        render 'edit'
      end
    end

  def destroy
    @profile.destroy
      redirect_to profiles_path, notice: "Profile was successfully destroyed."
  end

  private
    def set_profile
      @profile = current_user.profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def orders_count
    current_user.orders.count
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
  def services_count
    current_user.services.count
  end

  def orders_recieved_against_service
    current_user.services.map { |item| item.orders.count }.sum
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_field :bio %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">

  <p><% profile.picture.each do |pic| %>
      <%= image_tag pic, height: '350px', width: '700px' %>
    <% end %>
  </p>
  <p>
    <%= profile.first_name %> <%= profile.last_name %>
  </p>

</div>

app/views/profiles/edit.html.erb
<br>
<div class="card border-primary mb-3" style="width: 18rem;">
  <div class="card-header">
    <h4 class="title">Editing profile</h4>
  </div>
  <div class="card-body">
    <img src="..." class="card-img-top" alt="...">
    <%= render "form", profile: @profile %>

  </div>
  <div class="card-footer">
    <%= link_to "Show", @profile %>
  </div>
</div>

app/views/profiles/index.html.erb
<br>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container mb-4">
  <div class="row">
    <div class="col-lg-4 pb-5">
      <!-- Account Sidebar-->
      <div class="author-card pb-3">
        <div class="author-card-cover" style="background-image: url(https://bootdey.com/img/Content/flores-amarillas-wallpaper.jpeg);">
        </div>
        <div class="author-card-profile">
          <div class="author-card-avatar"><img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="Daniel Adams">
          </div>
          <div class="author-card-details">
            <h5 class="author-card-name text-lg" style="padding-top: 20px">
              <% if current_user.profile.present? %>
                  <%= current_user.profile.first_name %>
                  <%= current_user.profile.last_name %>
              <%end %>
            </h5>
            <span class="author-card-position">Bio: <%= current_user.profile.bio %></span>
            <span class="author-card-position">Joined: <%= current_user.created_at.strftime("#{current_user.created_at.day.ordinalize} %B %Y") %></span>
          </div>
        </div>
      </div>
      <div class="wizard">
        <nav class="list-group list-group-flush">
          <div style="background-color: #fff; height: 30px; padding-top: 5px; text-align:  center">
            <%= link_to 'Pets', pets_path %>
          </div>
          <div style="background-color: #fff; height: 30px; padding-top: 5px; text-align:  center">
            <%= link_to 'Services', services_path %>
          </div>
          <div style="background-color: #fff; height: 30px; padding-top: 5px; text-align:  center">
            <%= link_to 'My Orders', orders_user_orders_path %>
          </div>
          <div style="background-color: #fff; height: 30px; padding-top: 5px; text-align:  center">
            <%= link_to 'Orders Received', orders_path %>
          </div>
          <div style="background-color: #fff; height: 30px; padding-top: 5px; text-align:  center">
            <%= link_to 'Categories', types_path %>
          </div>

          <%= link_to "/pets_path", class: 'list-group-item active' do %>
            <div class="d-flex justify-content-between align-items-center">
              <div><i class="fa fa-shopping-bag mr-1 text-muted"></i>
                <div class="d-inline-block font-weight-medium text-uppercase">Pets</div>
              </div>
            </div>
          <%end%>
          <%#= link_to "/services_path", class: 'list-group-item active' do %>
<!--            <div class="d-flex justify-content-between align-items-center">-->
<!--              <div><i class="fa fa-shopping-bag mr-1 text-muted"></i>-->
<!--                <div class="d-inline-block font-weight-medium text-uppercase">Services</div>-->
<!--              </div>-->
<!--            </div>-->
          <%#end%>
          <%#= link_to "/orders_path", class: 'list-group-item active' do %>
<!--            <div class="d-flex justify-content-between align-items-center">-->
<!--              <div><i class="fa fa-shopping-bag mr-1 text-muted"></i>-->
<!--                <div class="d-inline-block font-weight-medium text-uppercase">Orders</div>-->
<!--              </div>-->
<!--            </div>-->
          <%#end%>
          <%#= link_to "/types_path", class: 'list-group-item active' do %>
<!--            <div class="d-flex justify-content-between align-items-center">-->
<!--              <div><i class="fa fa-shopping-bag mr-1 text-muted"></i>-->
<!--                <div class="d-inline-block font-weight-medium text-uppercase">Categories</div>-->
<!--              </div>-->
<!--            </div>-->
          <%#end%>
        </nav>
      </div>
    </div>
    <!-- Wishlist-->
    <div class="col-lg-8 pb-5">
      <% @post.each do |record| %>
      <div class="cart-item d-md-flex justify-content-between">
        <div class="px-3 my-3">
          <a class="cart-item-product" href="#">
            <div class="cart-item-product-thumb">
              <% if record.pictures.present?  %>
                <%= image_tag record.pictures.first %>
              <%end %>
            </div>
            <div class="cart-item-product-info">
              <h4 class="cart-item-product-title"><%= record.description %></h4>
            </div>
          </a>
        </div>
      </div>
      <%end %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Back", profiles_path %>
</div>

app/views/profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card w-75 border-primary mb-3">
  <% @profile.picture.each do |single_image| %>
    <%= image_tag single_image, height: '350px', width: '700px' %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title">
      <%= render @profile %>
    </h5>

    <%= link_to "Edit", edit_profile_path(@profile) %>

    <%= button_to "Destroy", @profile, method: :delete %>
  </div>
</div><br>