config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'pages/about'
  get 'orders/user_orders'

  devise_for :users

  resources :posts do
    resources :comments, only:  [:create, :destroy]
  end

  resources :pets

  get '/show_pet', to: 'pets#show_pet'
  get '/hide_pet', to: 'pets#hide_pet'

  resources :services do
    collection do
      get :all_services
    end
  end

  resources :orders
  resources :profiles
  resources :likes, only: [:create, :destroy]

  resources :home do
    get :post, on: :collection
  end

  resources :types

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :post
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, foreign_key: :parent_id
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: [:likeable_id, :likeable_type] }
  belongs_to :user
  belongs_to :user, optional: true
  belongs_to :post , optional: true
  belongs_to :likeable, polymorphic: true
end

app/models/order.rb
class Order < ApplicationRecord


  belongs_to :service
  belongs_to :user

  validates :title, presence: true
  validates :price, presence: true
  validates :service_id, presence: true

end

app/models/page.rb
class Page < ApplicationRecord

end

app/models/pet.rb
class Pet < ApplicationRecord

  belongs_to :user
  has_many :posts, dependent: :destroy
  belongs_to :type

  validates :name, presence: true
  validates :breed, presence: true
  validates :age, presence: true
  validates :gender, presence: true

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  belongs_to :pet
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many_attached :pictures, dependent: :destroy

end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user
  has_one_attached :picture, dependent: :destroy

end

app/models/service.rb
class Service < ApplicationRecord

  belongs_to :user
  has_many :orders, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

end

app/models/type.rb
class Type < ApplicationRecord

  belongs_to :user
  has_many :pets, dependent:  :destroy

end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :services, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :pets, dependent: :destroy
  has_many :types, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
    @like = current_user.likes.new(like_params)
    if @like.save
      redirect_back(fallback_location: 'index')
    end
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    likeable = @like.likeable
    @like.destroy
    redirect_back(fallback_location: 'index')
  end

  private

  def like_params
    params.require(:like).permit(:likeable_id, :likeable_type)
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [ :show, :edit, :update, :destroy ]
  def index
    @pet = Pet.new
    @pets = current_user.pets
    @types = current_user.types
    @pets = current_user.types.map { |item| item.pets }
  end

  def all_pets
    @pets = current_user.pets(created_at:'desc')
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def edit
    @types =  current_user.types
  end

  def show_pet
    @pet = Pet.find_by(id: params[:id])
    @pet.update!(:status => true)
    redirect_to pets_path
  end

  def hide_pet
    @pet = Pet.find_by(id: params[:id])
    @pet.update!(:status => false)
    redirect_to pets_path
  end


  def create
    @pet = current_user.pets.new(pet_params)

      if @pet.save
        redirect_to pet_path(@pet), notice: "Pet was successfully created."
      else
        render 'new'
      end
    end

  def update
    if @pet.update(pet_params)
        redirect_to pet_path(@pet), notice: "Pet was successfully updated."
      else
        render 'edit'
      end
  end


  def destroy
    @pet.destroy

    redirect_to pets_path, notice: "Pet was successfully destroyed."
  end

  private

    def set_pet
      @pet = current_user.pets.find(params[:id])
    end

    def pet_params
      params.require(:pet).permit(:name, :breed, :gender, :age, :description, :type_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def orders_count
    current_user.orders.count
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
  def services_count
    current_user.services.count
  end

  def orders_recieved_against_service
    current_user.services.map { |item| item.orders.count }.sum
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/likes/_button.html.erb
<div>
  <div style="float: left; padding-top: 15px">
    <%= likeable.likes.count %> Like
  </div>
 <div style="float: right">
    <% like = current_user.likes.find_by(likeable: likeable) %>
    <% if like.nil? %>
      <form action="/likes" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="like[likeable_id]" value="<%= likeable.id %>">
        <input type="hidden" name="like[likeable_type]" value="<%= likeable.class.to_s %>">
        <input type="submit" value="Like">
      </form>
    <% else %>
      <form action="<%= like_path(like) %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Unlike">
      </form>
    <% end %>
  </div>
</div>

app/views/pets/_form.html.erb
<div id="loginbox" class="mainbox">
  <div class="panel panel-info" >
    <div class="panel-body" >
      <%= form_with(model: pet) do |form| %>
        <label>Name</label>
        <div style="margin-bottom: 25px" class="input-group">
          <%= form.text_field :name, class: 'form-control', style: 'border-radius:10px'%>
          <%# if pet.errors.any? %>
            <%# pet.errors.each do |error| %>
<!--              <div class="alert alert-danger col-sm-12">><%#= error.full_message %></div>-->
            <%# end %>
          <%# end %>
        </div>
        <label>Breed</label>
        <div style="margin-bottom: 25px" class="input-group">
          <%= form.text_field :breed, class: 'form-control', style: 'border-radius:10px' %>
        </div>
        <label>Gender</label>
        <div style="margin-bottom: 25px" class="input-group">
          <%= form.text_field :gender, class: 'form-control', style: 'border-radius:10px' %>
        </div>
        <label>Age</label>
        <div style="margin-bottom: 25px" class="input-group">
          <%= form.text_field :age, class: 'form-control', style: 'border-radius:10px' %>
        </div>
        <label>Bio</label>
        <div style="margin-bottom: 25px" class="input-group">
          <%= form.text_field :description, class: 'form-control', style: 'border-radius:10px' %>
        </div>
        <div style="margin-bottom: 25px" class="input-group">
          <p class="list-group-item">Select Category : <%= form.collection_select :type_id, @types, :id, :name, include_blank: true %></p>
        </div>
        <%= form.submit class:'btn btn-primary' %>
      <%end%>
    </div>
  </div>
</div>

app/views/pets/_pet.html.erb
<div class="col-md-4">
  <div class="card user-card">
    <div class="card-header">
      <h5>by: <%= current_user.profile.first_name %> <%= current_user.profile.last_name %></h5>
      <%= link_to "EDIT", edit_pet_path(pet) %> | <%= button_to "DELETE", pet_path(pet), method: :delete %>
      <%= link_to "Hide",hide_pet_path(id: pet.id)  %> | <%= link_to "Show", show_pet_path(id: pet.id)  %>
    </div>
<!--    <p class="text-muted">Visiablity Status: <%#= pet.status %></p>-->
    <div class="card-block">
      <hr><p class="text-muted"><%= pet.type.name %></p><hr>
      <div class="user-image">
        <img src="https://bootdey.com/img/Content/avatar/avatar7.png" class="img-radius" alt="User-Profile-Image">
      </div>
      <h6 class="f-w-600 m-t-25 m-b-10">Name: <%= pet.name %></h6>
      <p class="text-muted">Breed: <%= pet.breed %></p>
      <p class="text-muted">Gender: <%= pet.gender %></p>
      <p class="text-muted m-t-15">Age: <%= pet.age %> </p>
      <hr>
      <p class="m-t-15 text-muted"><%= pet.description %> </p>
    </div>
  </div>
</div>

app/views/pets/all_pets.html.erb
<div class="container-fluid mt-5">
  <div class="row">
    <% @pets.each do |pet| %>
      <%= render pet %>
    <% end %>
  </div>
</div>

app/views/pets/edit.html.erb
<h1>Edit Pet</h1>

<%= render "form", pet: @pet %>

app/views/pets/index.html.erb
<div class="container-fluid mt-5">
  <div class="row">
    <div class="col-md-4">
      <div class="card user-card">
        <div class="card-header">
          <h5>Add New Pet</h5>
          <p style="color: red"><%= alert %></p>
        </div>
        <div class="card-block">
          <%= render "form", pet: @pet %>
        </div>
      </div>
    </div>
    <% @pets.each do |pet| %>
      <%= render pet %>
    <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<br>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Add Pet</h5>
  </div>
</div>

<br>

<%= render "form", pet: @pet %>

app/views/pets/show.html.erb
<p class="flash" style="color: green"><%= notice %></p>

<%= render @pet %>

<div>
  <%= link_to "Edit", edit_pet_path(@pet) %> |
  <%= link_to "Back", pets_path %>

  <%= button_to "Destroy", @pet, method: :delete %>
</div>