config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'pages/about'
  get 'orders/user_orders'

  devise_for :users

  resources :posts do
    resources :comments, only:  [:create, :destroy]
  end

  resources :pets

  get '/show_pet', to: 'pets#show_pet'
  get '/hide_pet', to: 'pets#hide_pet'

  resources :services do
    collection do
      get :all_services
    end
  end

  resources :orders
  resources :profiles
  resources :likes, only: [:create, :destroy]

  resources :home do
    get :post, on: :collection
  end

  resources :types

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :post
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, foreign_key: :parent_id
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: [:likeable_id, :likeable_type] }
  belongs_to :user
  belongs_to :user, optional: true
  belongs_to :post , optional: true
  belongs_to :likeable, polymorphic: true
end

app/models/order.rb
class Order < ApplicationRecord


  belongs_to :service
  belongs_to :user

  validates :title, presence: true
  validates :price, presence: true
  validates :service_id, presence: true

end

app/models/page.rb
class Page < ApplicationRecord

end

app/models/pet.rb
class Pet < ApplicationRecord

  belongs_to :user
  has_many :posts, dependent: :destroy
  belongs_to :type

  validates :name, presence: true
  validates :breed, presence: true
  validates :age, presence: true
  validates :gender, presence: true

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  belongs_to :pet
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many_attached :pictures, dependent: :destroy

end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user
  has_one_attached :picture, dependent: :destroy

end

app/models/service.rb
class Service < ApplicationRecord

  belongs_to :user
  has_many :orders, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

end

app/models/type.rb
class Type < ApplicationRecord

  belongs_to :user
  has_many :pets, dependent:  :destroy

end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :services, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :pets, dependent: :destroy
  has_many :types, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def orders_count
    current_user.orders.count
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
  def services_count
    current_user.services.count
  end

  def orders_recieved_against_service
    current_user.services.map { |item| item.orders.count }.sum
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Pet App", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>

        <li class="nav-link active">
          <%= current_user.email%>
        </li>

        <li class="nav-item active">
          <%= link_to "Post", posts_path, class:"nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Pets", pets_path, class:"nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item active ">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

      <% else %>

        <li class="nav-item active">
          <%= link_to "Sign In", user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

      <% end %>

    </ul>

  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>