config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'pages/about'
  get 'orders/user_orders'

  devise_for :users

  resources :posts do
    resources :comments, only:  [:create, :destroy]
  end

  resources :pets

  get '/show_pet', to: 'pets#show_pet'
  get '/hide_pet', to: 'pets#hide_pet'

  resources :services do
    collection do
      get :all_services
    end
  end

  resources :orders
  resources :profiles
  resources :likes, only: [:create, :destroy]

  resources :home do
    get :post, on: :collection
  end

  resources :types

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :post
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, foreign_key: :parent_id
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: [:likeable_id, :likeable_type] }
  belongs_to :user
  belongs_to :user, optional: true
  belongs_to :post , optional: true
  belongs_to :likeable, polymorphic: true
end

app/models/order.rb
class Order < ApplicationRecord


  belongs_to :service
  belongs_to :user

  validates :title, presence: true
  validates :price, presence: true
  validates :service_id, presence: true

end

app/models/page.rb
class Page < ApplicationRecord

end

app/models/pet.rb
class Pet < ApplicationRecord

  belongs_to :user
  has_many :posts, dependent: :destroy
  belongs_to :type

  validates :name, presence: true
  validates :breed, presence: true
  validates :age, presence: true
  validates :gender, presence: true

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  belongs_to :pet
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many_attached :pictures, dependent: :destroy

end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user
  has_one_attached :picture, dependent: :destroy

end

app/models/service.rb
class Service < ApplicationRecord

  belongs_to :user
  has_many :orders, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

end

app/models/type.rb
class Type < ApplicationRecord

  belongs_to :user
  has_many :pets, dependent:  :destroy

end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :services, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :pets, dependent: :destroy
  has_many :types, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [ :show, :edit, :update, :destroy ]
  def index
    @pet = Pet.new
    @pets = current_user.pets
    @types = current_user.types
    @pets = current_user.types.map { |item| item.pets }
  end

  def all_pets
    @pets = current_user.pets(created_at:'desc')
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def edit
    @types =  current_user.types
  end

  def show_pet
    @pet = Pet.find_by(id: params[:id])
    @pet.update!(:status => true)
    redirect_to pets_path
  end

  def hide_pet
    @pet = Pet.find_by(id: params[:id])
    @pet.update!(:status => false)
    redirect_to pets_path
  end


  def create
    @pet = current_user.pets.new(pet_params)

      if @pet.save
        redirect_to pet_path(@pet), notice: "Pet was successfully created."
      else
        render 'new'
      end
    end

  def update
    if @pet.update(pet_params)
        redirect_to pet_path(@pet), notice: "Pet was successfully updated."
      else
        render 'edit'
      end
  end


  def destroy
    @pet.destroy

    redirect_to pets_path, notice: "Pet was successfully destroyed."
  end

  private

    def set_pet
      @pet = current_user.pets.find(params[:id])
    end

    def pet_params
      params.require(:pet).permit(:name, :breed, :gender, :age, :description, :type_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :show, :edit, :update, :destroy ]

  def index
    @all_post = Post.all.order(created_at:'desc')
    @post = Post.new
    @pets = current_user.pets
    @posts = current_user.pets.map { |item| item.posts }
    @service = current_user.services.limit(3)
    @order = current_user.orders.limit(3)
    @type = current_user.types.limit(3)
    @pet = current_user.pets.limit(3)
  end

  def show
  end

  def new
    @post = Post.new
    @pets = Pet.where(status: true)
  end

  def edit
    @pets = current_user.pets
    if @post.present?
      @post
    else
      redirect_to posts_path, alert: "This post does not belong to you."
    end
  end

  def create
    @post = current_user.posts.new(post_params)
      if @post.save
        redirect_to post_path(@post), notice: "Post was successfully created."
      else
        render 'new'
      end
  end

  def update
      if @post.update(post_params)
        redirect_to post_path(@post), notice: "Post was successfully updated."
      else
        render 'edit'
      end
  end

  def destroy
    if @post.present?
      @post.destroy
      redirect_to posts_path, notice: "Post was successfully destroyed."
    else
      redirect_to posts_path, alert: "This post does not belong to you."
    end
  end

  private

    def set_post
      @post = current_user.posts.find_by(id:params[:id])
    end

    def post_params
      params.require(:post).permit(:description, :pet_id, pictures: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def orders_count
    current_user.orders.count
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
  def services_count
    current_user.services.count
  end

  def orders_recieved_against_service
    current_user.services.map { |item| item.orders.count }.sum
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/posts/_form.html.erb
<%#= form_with(model: post) do |form| %>
  <%# if post.errors.any? %>
<!--    <div style="color: red">-->
<!--      <h2><%#= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>-->

<!--      <ul>-->
        <%# post.errors.each do |error| %>
<!--          <li><%#= error.full_message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

<!--  <div class="card">-->
<!--    <div class="card-header">-->
<!--      <h4 class="card-text"> New Post </h4>-->
<!--    </div>-->
<!--    <div class="card-body">-->
      <%#= form.label :description, style: "display: block" %>
      <%#= form.text_area :description %>
<!--      <div>-->
        <%#= form.file_field :pictures, multiple: true %>
<!--      </div><br>-->
<!--    </div>-->
<!--    <div class="card-footer ">-->
<!--      <div style="width: 50%; float: right">-->
<!--        <p class="float-right">-->
          <%#= form.submit %>
<!--        </p>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<%# end %>

<%= form_with(model: post) do |form| %>
  <div class="card gedf-card">
    <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="posts" aria-selected="true">Post</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="images-tab" data-toggle="tab" role="tab" aria-controls="images" aria-selected="false" href="#images">Images</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pets-tab" data-toggle="tab" href="#pets" role="tab" aria-controls="pets" aria-selected="false">Pet</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">
        <div class="form-group">
          <label class="sr-only" for="message">post</label>
          <%= form.text_area :description ,id: "message",class: "form-control", placeholder: "What are you thinking?"%>
        </div>
      </div>
      <div class="tab-pane fade" id="images" role="tabpanel" aria-labelledby="images-tab">
        <div class="form-group">
          <div class="custom-file">
            <%= form.file_field :pictures, multiple: true,class: "custom-file-input",id: "customFile"  %>
            <label class="custom-file-label" for="customFile">Upload image</label>
          </div>
        </div>
        <div class="py-4"></div>
      </div>
      <div class="tab-pane fade" id="pets" role="tabpanel" aria-labelledby="pets-tab">
            <p class="list-group-item">Select Pet <%= form.collection_select :pet_id, @pets, :id, :name, include_blank: true %></p>
        <div class="py-4"></div>
      </div>
    </div>
    <div>
      <div style="float: right; height: 55px">
        <%= form.submit class: "btn btn-primary"%>
      </div>
<!--      <div class="btn-group">-->
<!--        <button id="btnGroupDrop1" type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          <p class="">Privacy</p>-->
<!--        </button>-->
<!--        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">-->
<!--          <a class="dropdown-item" href="#"><i class="fa fa-globe"></i> Public </a>-->
<!--          <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Private </a>-->
<!--        </div>-->
<!--      </div>-->
    </div>
  </div>
</div>
<%end%>

app/views/posts/_post.html.erb
      <div class="card gedf-card" id=hidepost>
        <div class="card-header">
          <div class="d-flex justify-content-between align-items-center">
            <div class="d-flex justify-content-between align-items-center">
              <div class="mr-2">
                <img class="rounded-circle" width="45" src="https://picsum.photos/50/50" alt="">
              </div>
              <div class="ml-2">
                <div class="h5 m-0">
                  <%= post.user.profile.first_name %> <%= post.user.profile.last_name %>
                </div>
              </div>
              </div>
              <%= link_to "EDIT", edit_post_path(post) %> | <%= button_to "DELETE", post_path(post), method: :delete %>
          </div>

        </div>
        <div class="card-body">
          <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o">posted </i><%= time_ago_in_words(post.created_at) %></div>
          <p class="card-text">
            <%= post.description %>
          </p>
          <div>
            <% post.pictures.each do |pic| %>
                <%= image_tag pic ,style: "width:100%;height:50%"%>
            <% end %>
            <span class="badge badge-primary"><%= post.pet.name %></span>
          </div>
        </div>
        <div class="card-footer" style="height: 85px">
          <div style="width: 50px; float: left; padding-top: 20px">
            <%= post.likes.count %> Like
          </div>
            <div class="float-right">
              <% like = current_user.likes.find_by(likeable: post) %>
              <% if like.nil? %>
                <form action="/likes" method="post">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                  <input type="hidden" name="like[likeable_id]" value="<%= post.id %>">
                  <input type="hidden" name="like[likeable_type]" value="<%= post.class.to_s %>">
                  <input type="submit" value="Like">
                </form>
              <% else %>
                <form action="<%= like_path(like) %>" method="post">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                  <input type="hidden" name="_method" value="DELETE">
                  <input type="submit" value="Unlike">
                </form>
              <% end %>
            </div>
        </div>
        <div style="height: 40px">
          <%= render partial: 'comments/form', locals: { post: post, parent: nil } %>
        </div>
        <div class="card-body" style="margin-top: 20px">
          <% post.comments.each do |comment| %>
              <div>
                <div style="width: 50%; float: left">
                  <p>
                    <small> by <%= comment.user.profile.first_name %></small><br>
                    <%= comment.content %> <br>
                    <small><%= time_ago_in_words(comment.created_at) %> ago</small>
                  </p>
                </div>
                <div style="width: 50%; float: right">
                  <span style="float: right"> <%= render partial: 'likes/button', locals: { likeable: comment} %></span>
                </div>
              </div>
            <article>
              <a href="#" class="comment-form-display reply" >reply</a>

              <div class="comment-form">
                <%= render partial: 'comments/form', locals: { post: comment.post, parent: comment } %>
              </div>
              <div class="sub-comment">
                <%= render comment.comments.order(id: :desc)%>
              </div>
            </article>
            <div>
              <%= render post.comments.where(parent_id: nil).includes(:user).order(id: :desc) %>
            </div>
          <% end %>
        </div>
      </div>


        <script>
            document.querySelectorAll('.comment-form-display').forEach((el) => {
                el.addEventListener('click', (ev) => {
                    ev.preventDefault();
                    el.nextElementSibling.style = 'display: block;'
                })
            })
        </script>

<!--      <script>-->
<!--        $(document).ready(function (){-->
<!--            $(".show_reply").click(function (){-->
<!--                alert(this.attr("id"));-->
<!--            });-->
<!--        })-->
<!--      </script>-->


<!--      <script>-->
<!--          function hideInput() {-->
<!--              var postDiv = document.getElementById("hidepost");-->
<!--              postDiv.style.display === "block" ?  postDiv.style.display = 'none' : postDiv.style.display = 'block';-->
<!--          }-->
<!--      </script>-->

app/views/posts/edit.html.erb
<p>
  <%= render "form", post: @post %>
</p>

app/views/posts/index.html.erb
<div class="container-fluid gedf-wrapper">
  <div class="row">
    <div class="col-md-3">
      <div class="card">
        <div class="card-body">
          <div class="h5"><%= link_to "#{current_user.profile.first_name}", profiles_path %></div>
          <div class="h7 text-muted">Bio : <%= current_user.profile.bio %></div>
          <div class="h7">
          </div>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="h6 text-muted">Services</div>
            <div class="h5"><%= services_count %></div>
          </li>
          <li class="list-group-item">
            <div class="h6 text-muted">Orders Place By You</div>
            <div class="h5"><%= orders_count %></div>
          </li>
          <li class="list-group-item">
            <div class="h6 text-muted">Orders Recieved</div>
            <div class="h5"><%= orders_recieved_against_service %></div>
          </li>
          <li class="list-group-item">User info <%= link_to 'See', profiles_path %></li>
        </ul>
      </div>
      <div class="card gedf-card">
        <div class="card-body">
          <h5 class="card-title">Your Pet Category</h5>
          <%= link_to 'All Categories', types_path, class: 'card-link' %>
          <hr>
          <% @type.each do |record| %>
            <h4 class="card-subtitle mb-2 text-muted">Name: <%= record.name %></h4>
            <%= link_to "Details", types_path, class: "card-link" %>
          <%end%>
          <hr>
          <%= link_to 'Add New Category', types_path, class: 'card-link' %>
        </div>
      </div>
      <div class="card gedf-card">
        <div class="card-body">
          <h5 class="card-title">Your Pet</h5>
          <%= link_to 'All Pets', pets_path, class: 'card-link' %>
          <hr>
          <% @pet.each do |record| %>
            <h4 class="card-subtitle mb-2 text-muted">Name: <%= record.name %><small><i>(<%= record.type.name %>)</i></small></h4>
            <%= link_to "Details", pets_path, class: "card-link" %>
          <%end%>
          <hr>
          <%= link_to 'Add New Pet', pets_path, class: 'card-link' %>
        </div>
      </div>
    </div>
    <div class="col-md-6 gedf-main">
        <%= render 'posts/form', post: @post %>
          <p style="color: red"><%= alert %></p>
          <% @all_post.each do |post| %>
            <% if post.present? %>
              <% if post.pet.status == true %>
                <%= render post %>
              <% end %>
            <%end%>
        <% end %>
    </div>
    <div class="col-md-3">
      <div class="card gedf-card">
        <div class="card-body">
          <h5 class="card-title">Your Services</h5>
          <%= link_to 'All Services', services_path, class: 'card-link' %>
          <hr>
          <% @service.each do |record| %>
          <h4 class="card-subtitle mb-2 text-muted">Name: <%= record.title %></h4>
            <%= link_to "Details", services_path, class: "card-link" %>
          <%end%>
          <hr>
          <%= link_to 'Add New Service', services_path, class: 'card-link' %>
        </div>
      </div>
      <div class="card gedf-card">
        <div class="card-body">
          <h5 class="card-title">Your Orders</h5>
          <%= link_to 'All Orders', orders_user_orders_path, class: 'card-link' %>
          <hr>
          <% @order.each do |record| %>
            <h4 class="card-subtitle mb-2 text-muted">Name: <%= record.title %><small><i>(<%= record.service.title %>)</i></small></h4>
            <%= link_to "Details", orders_user_orders_path, class: "card-link" %>
          <% end %>
          <hr>
          <%= link_to 'Add New Order', orders_path, class: 'card-link' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<br>
<div class="card" id="hidepost">
  <div class="card-header">
    <div style="width: 50%; float: left">
      <%= @post.user.full_name %> <br>
      <small>posted <%= time_ago_in_words(@post.created_at) %> ago.</small>
    </div>
    <div style="width: 50%; float: right">
       <p style="float: right; margin-top: 15px">
        <%= link_to "Edit", edit_post_path(@post) %> |
        <%= link_to "Back", posts_path %>
      </p>
    </div>
  </div>
  <div class="card-body">
    <p class="card-text"><%= @post.description %></p>
    <p>
      <% @post.pictures.each do |single_image| %>
        <%= image_tag single_image, height: '350px', width: '700px' %>
      <% end %>
    </p>
  </div>
  <div class="card-footer">
    <%= render partial: 'likes/button', locals: { likeable: @post } %>
    <div class="fl">
      <%= render partial: 'comments/form', locals: { post: @post, parent: nil } %>
    </div>
  </div>
  <div class="card-body">
    <hr/>
    <div class="scroll">
      <%= render @post.comments.where(parent_id: nil).includes(:user).order(id: :desc) %>
    </div>

  </div>
</div>
<br>